### ISSUE TITLE
Web app

### ISSUE THREAD

**Issue by Lyrenhex** [Scratso/Ave#26]
Ave is built with HTML, CSS, and JavaScript (I swear I've said this a thousand times now).

Therefore, it could be used also as a web-based app for Chrome, Safari, and Firefox. (And maybe IE and Edge).

This would benefit many users as they wouldn't have to install a program to use Ave -- it could be used on the web entirely.

Of course, there would be some limitations:
- "Server Profiles" would have to be saved in cookies; which themselves would have to expire (perhaps if we set them to expire 5 years after creation?)
- CSS would have to be changed to comply with vendor prefixes; `-moz`, `-webkit`, etc.

**Comment by Scratso** [comment]
Wait; why not just stick the entire site in `gh-pages`, and set a custom domain on the git repo?

**Comment by Scratso** [comment]
scrap that last bit, but can we use express?

**Comment by Lyrenhex** [comment]
Not important. Might re-open when the desktop app is less complex as it is.
